#!groovy
@Library('jenkins-pipeline-lib') _

pipeline
{
  agent any
  triggers
  {
    //At 04:00 on every day-of-week from Monday through Friday.
    pollSCM('H 4 * * 1-5')
  }
  environment
  {
    GIT_CHANGE_LOG = gitChangeLog(currentBuild.changeSets)
  }
  stages
  {
    stage('Setup')
    {
      steps
      {
        gitTagPreBuild "${BUILD_NUMBER}"
      }
    }
    stage('Build')
    {
      steps
      {
        sh 'mvn install'
      }
    }
    stage('Archive')
    {
      steps
      {
        archiveArtifacts 'target/*.hpi'
      }
      post
      {
        failure
        {
          sendNotifications 'ARCHIVE_ERROR'
        }
      }
    }
  }
  post
  {
    always
    {
      // Report Status
      sendNotifications(currentBuild.currentResult)
      gitTagCleanup "${BUILD_NUMBER}"

      junit 'target/**/*Test.xml'
    }
    success
    {
      gitTagSuccess "${BUILD_NUMBER}"
    }
    failure
    {
    /*
      * This job does not have a GitHub configuration,
      * so we need to create a dummy config
      */
      githubSetConfig('4c01f168-ca25-483e-bc6d-8d105fc5fb70')
      githubFileIssue()
      emailNotify(currentBuild.currentResult)
    }
  }
}
